// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/layouts/default.vue')['default']
    IronCard: typeof import('./src/components/IronCard.vue')['default']
    IronLogotype: typeof import('./src/components/IronLogotype.vue')['default']
    IronMove: typeof import('./src/components/IronMove.vue')['default']
    IronParagraph: typeof import('./src/components/IronParagraph.vue')['default']
    IronSourceInfo: typeof import('./src/components/IronSourceInfo.vue')['default']
    MarkdownRouterLink: typeof import('./src/components/MarkdownRouterLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableOfContents: typeof import('./src/components/TableOfContents.vue')['default']
  }
}
