// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommunityIcon: typeof import('./src/components/icons/CommunityIcon.vue')['default']
    'Components.d': typeof import('./node_modules/vuetify/lib/labs/components.d.ts')['default']
    DefaultLayout: typeof import('./src/layouts/default.vue')['default']
    DocumentationIcon: typeof import('./src/components/icons/DocumentationIcon.vue')['default']
    EcosystemIcon: typeof import('./src/components/icons/EcosystemIcon.vue')['default']
    'Fa.d': typeof import('./node_modules/vuetify/lib/iconsets/fa.d.ts')['default']
    'Fa4.d': typeof import('./node_modules/vuetify/lib/iconsets/fa4.d.ts')['default']
    'FaSvg.d': typeof import('./node_modules/vuetify/lib/iconsets/fa-svg.d.ts')['default']
    FrameworkLink: typeof import('./src/components/FrameworkLink.vue')['default']
    'Index.d': typeof import('./node_modules/vuetify/lib/index.d.ts')['default']
    IronLogotype: typeof import('./src/components/IronLogotype.vue')['default']
    MarkdownRouterLink: typeof import('./src/components/MarkdownRouterLink.vue')['default']
    'Md.d': typeof import('./node_modules/vuetify/lib/iconsets/md.d.ts')['default']
    'Md1.d': typeof import('./node_modules/vuetify/lib/blueprints/md1.d.ts')['default']
    'Md2.d': typeof import('./node_modules/vuetify/lib/blueprints/md2.d.ts')['default']
    'Md3.d': typeof import('./node_modules/vuetify/lib/blueprints/md3.d.ts')['default']
    'Mdi.d': typeof import('./node_modules/vuetify/lib/iconsets/mdi.d.ts')['default']
    'MdiSvg.d': typeof import('./node_modules/vuetify/lib/iconsets/mdi-svg.d.ts')['default']
    Moves: typeof import('./src/components/Moves.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceInfo: typeof import('./src/components/SourceInfo.vue')['default']
    SupportIcon: typeof import('./src/components/icons/SupportIcon.vue')['default']
    TableOfContents: typeof import('./src/components/TableOfContents.vue')['default']
    ToolingIcon: typeof import('./src/components/icons/ToolingIcon.vue')['default']
    VLayout: typeof import('./src/layouts/v.vue')['default']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer']
    'VueI18n.d': typeof import('./node_modules/vuetify/lib/locale/adapters/vue-i18n.d.ts')['default']
    Vuetify: typeof import('./node_modules/vuetify/dist/vuetify.js')['default']
    'Vuetify.d': typeof import('./node_modules/vuetify/dist/vuetify.d.ts')['default']
    'Vuetify.esm': typeof import('./node_modules/vuetify/dist/vuetify.esm.js')['default']
    'Vuetify.min': typeof import('./node_modules/vuetify/dist/vuetify.min.js')['default']
    VuetifyLabs: typeof import('./node_modules/vuetify/dist/vuetify-labs.js')['default']
    'VuetifyLabs.d': typeof import('./node_modules/vuetify/dist/vuetify-labs.d.ts')['default']
    'VuetifyLabs.esm': typeof import('./node_modules/vuetify/dist/vuetify-labs.esm.js')['default']
  }
}
