// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommunityIcon: typeof import('./src/components/icons/CommunityIcon.vue')['default']
    DefaultLayout: typeof import('./src/layouts/default.vue')['default']
    DocumentationIcon: typeof import('./src/components/icons/DocumentationIcon.vue')['default']
    EcosystemIcon: typeof import('./src/components/icons/EcosystemIcon.vue')['default']
    FrameworkLink: typeof import('./src/components/FrameworkLink.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    MarkdownRouterLink: typeof import('./src/components/MarkdownRouterLink.vue')['default']
    Moves: typeof import('./src/components/Moves.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceInfo: typeof import('./src/components/SourceInfo.vue')['default']
    SupportIcon: typeof import('./src/components/icons/SupportIcon.vue')['default']
    ToolingIcon: typeof import('./src/components/icons/ToolingIcon.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
